exclude:
  - README.md
  - Makefile
  - Dockerfile
  - Jenkinsfile

collections:
  pages:
    output: true
    permalink: /:title

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [local]
  blanklines: false
  startings: [html, head, body]
